/// Flutter icons Pc_builder
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pc_builder
///      fonts:
///       - asset: fonts/pc-builder.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PcBuilderIcons {
  PcBuilderIcons._();

  static const _kFontFam = 'pc-builder';
  static const String? _kFontPkg = null;

  static const IconData gpu = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hdd = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleIcon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData internet = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motherboard = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData powerSupply = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData priceDown = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData priceUp = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData processor = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ram = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ssdCard = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData topSecret = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkMark = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computerCase = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
